name: Push + Manual Workflow

on:
  push:
    branches:
      - main   # triggers on push to main


jobs:
  print-message:
    runs-on: ubuntu-latest

    steps:
      - name: Print message
        run: echo "Workflow run 🚀"
